#!/bin/bash
usage() {
    echo USAGE: bagger OPTION
    echo "options: -a : all topics"  
    echo "         -i : imu pose data"
    echo "         -t : internal and external temperature"
    echo "         -c : camera data; i.e. camera info, image rectified and color image from up and down cameras"
    echo "         -d : depth sensor data"
}
command_arguments=''
for arg in $@; do

	case $arg in
		'-a' )
			command_arguments="$command_arguments electrical_interface/pose"
			command_arguments="$command_arguments electrical_interface/depth"
			command_arguments="$command_arguments status/temperature electrical_interface/temperature"
			command_arguments="$command_arguments camera_down/camera/camera_info camera_down/camera/image_rect_color camera_down/camera/image_color"
			command_arguments="$command_arguments camera_front_left/camera/camera_info camera_front_left/camera/image_rect_color camera_front_left/camera/image_color"
			;;
		'-i' )
			command_arguments="$command_arguments electrical_interface/pose"
			;;
		'-t' )
			command_arguments="$command_arguments status/temperature electrical_interface/temperature"
			;;	
		'-c' )
			#down camera:
                        command_arguments="$command_arguments camera_down/camera/camera_info camera_down/camera/image_rect_color camera_down/camera/image_color  "
			#front camera
                        command_arguments="$command_arguments camera_front_left/camera/camera_info camera_front_left/camera/image_rect_color camera_front_left/camera/image_color  "
                        ;;
		'-d' )
			command_arguments="$command_arguments electrical_interface/depth"
			;;
		* )
			usage
                        ;;
	esac

done

rosbag record $command_arguments -O ../../bag-$(date +%s)

