# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Feedback.ui'
#
# Created: Mon Nov 18 13:41:23 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(573, 512)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Pictures/Only-Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 271, 81))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/Pictures/Landscape-Logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 90, 211, 121))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalSlider_3 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_3.setMinimum(-100)
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.verticalLayout_3.addWidget(self.horizontalSlider_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalSlider_2 = QtGui.QSlider(self.layoutWidget)
        self.verticalSlider_2.setMinimum(-99)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName(_fromUtf8("verticalSlider_2"))
        self.horizontalLayout_2.addWidget(self.verticalSlider_2)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 240, 162, 76))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.SquO = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.SquO.setMargin(0)
        self.SquO.setObjectName(_fromUtf8("SquO"))
        self.square = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.square.setObjectName(_fromUtf8("square"))
        self.SquO.addWidget(self.square)
        self.XTri = QtGui.QVBoxLayout()
        self.XTri.setObjectName(_fromUtf8("XTri"))
        self.triangle = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.triangle.setObjectName(_fromUtf8("triangle"))
        self.XTri.addWidget(self.triangle)
        self.x = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.x.setObjectName(_fromUtf8("x"))
        self.XTri.addWidget(self.x)
        self.SquO.addLayout(self.XTri)
        self.o = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.o.setObjectName(_fromUtf8("o"))
        self.SquO.addWidget(self.o)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 260, 181, 78))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.left = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.left.setObjectName(_fromUtf8("left"))
        self.horizontalLayout_4.addWidget(self.left)
        self.UpDown = QtGui.QVBoxLayout()
        self.UpDown.setObjectName(_fromUtf8("UpDown"))
        self.up = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.up.setObjectName(_fromUtf8("up"))
        self.UpDown.addWidget(self.up)
        self.down = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.down.setObjectName(_fromUtf8("down"))
        self.UpDown.addWidget(self.down)
        self.horizontalLayout_4.addLayout(self.UpDown)
        self.right = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.right.setObjectName(_fromUtf8("right"))
        self.horizontalLayout_4.addWidget(self.right)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 211, 121))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalSlider = QtGui.QSlider(self.layoutWidget1)
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalSlider = QtGui.QSlider(self.layoutWidget1)
        self.verticalSlider.setMinimum(-99)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.horizontalLayout.addWidget(self.verticalSlider)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 360, 213, 54))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.AutonomusRB = QtGui.QRadioButton(self.layoutWidget2)
        self.AutonomusRB.setChecked(True)
        self.AutonomusRB.setObjectName(_fromUtf8("AutonomusRB"))
        self.verticalLayout_2.addWidget(self.AutonomusRB)
        self.ManualRB = QtGui.QRadioButton(self.layoutWidget2)
        self.ManualRB.setObjectName(_fromUtf8("ManualRB"))
        self.verticalLayout_2.addWidget(self.ManualRB)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.changeStatus = QtGui.QPushButton(self.layoutWidget2)
        self.changeStatus.setToolTip(_fromUtf8(""))
        self.changeStatus.setWhatsThis(_fromUtf8(""))
        self.changeStatus.setObjectName(_fromUtf8("changeStatus"))
        self.horizontalLayout_3.addWidget(self.changeStatus)
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(270, 240, 101, 108))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.r1 = QtGui.QCheckBox(self.layoutWidget_2)
        self.r1.setObjectName(_fromUtf8("r1"))
        self.verticalLayout_5.addWidget(self.r1)
        self.r2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.r2.setObjectName(_fromUtf8("r2"))
        self.verticalLayout_5.addWidget(self.r2)
        self.l1 = QtGui.QCheckBox(self.layoutWidget_2)
        self.l1.setObjectName(_fromUtf8("l1"))
        self.verticalLayout_5.addWidget(self.l1)
        self.l2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.l2.setObjectName(_fromUtf8("l2"))
        self.verticalLayout_5.addWidget(self.l2)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(420, 330, 101, 108))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.select = QtGui.QCheckBox(self.widget)
        self.select.setObjectName(_fromUtf8("select"))
        self.verticalLayout_4.addWidget(self.select)
        self.start = QtGui.QCheckBox(self.widget)
        self.start.setObjectName(_fromUtf8("start"))
        self.verticalLayout_4.addWidget(self.start)
        self.l3 = QtGui.QCheckBox(self.widget)
        self.l3.setObjectName(_fromUtf8("l3"))
        self.verticalLayout_4.addWidget(self.l3)
        self.r3 = QtGui.QCheckBox(self.widget)
        self.r3.setObjectName(_fromUtf8("r3"))
        self.verticalLayout_4.addWidget(self.r3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PS3 Controller Input Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.square.setText(QtGui.QApplication.translate("MainWindow", "Squ", None, QtGui.QApplication.UnicodeUTF8))
        self.triangle.setText(QtGui.QApplication.translate("MainWindow", "Tri", None, QtGui.QApplication.UnicodeUTF8))
        self.x.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.o.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.left.setText(QtGui.QApplication.translate("MainWindow", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.right.setText(QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.AutonomusRB.setText(QtGui.QApplication.translate("MainWindow", "Autonomous", None, QtGui.QApplication.UnicodeUTF8))
        self.ManualRB.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.changeStatus.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.r1.setText(QtGui.QApplication.translate("MainWindow", "r1", None, QtGui.QApplication.UnicodeUTF8))
        self.r2.setText(QtGui.QApplication.translate("MainWindow", "r2", None, QtGui.QApplication.UnicodeUTF8))
        self.l1.setText(QtGui.QApplication.translate("MainWindow", "l1", None, QtGui.QApplication.UnicodeUTF8))
        self.l2.setText(QtGui.QApplication.translate("MainWindow", "l2", None, QtGui.QApplication.UnicodeUTF8))
        self.select.setText(QtGui.QApplication.translate("MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("MainWindow", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.l3.setText(QtGui.QApplication.translate("MainWindow", "l3", None, QtGui.QApplication.UnicodeUTF8))
        self.r3.setText(QtGui.QApplication.translate("MainWindow", "r3", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("MainWindow", "Close the window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))

import RobosubUI_rc
