#!/usr/bin/env python2.7

'''
I think the use of a timer in this node could be improved.
The problem is that gazebo publishes modelStates at very high frequency,
and we want to publish depth at a much lower frequency.

I recommend changing the implementation as follows:
    The modelStates callback should update a depth variable every time it is called.
    A ROS timer should be called to publish the value in this variable ever x seconds in a separate callback function
    http://wiki.ros.org/roscpp_tutorials/Tutorials/Timers

-Nick Speal

'''


import rospy
from std_msgs.msg import Float64
from geometry_msgs.msg import PoseStamped
from gazebo_msgs.msg import ModelStates

time = None

def callback(modelStates):
    global time
    if time:
        if (rospy.get_time() - time) > 0.03:
            index = modelStates.name.index('robot')
            pub.publish(10- modelStates.pose[index].position.z)
            time = rospy.get_time()
    else:
        time = rospy.get_time()


# Init the ros node, subscribers and publishers
# And run the node
def init():
    global pub, time
    rospy.init_node('sim_depth')

    # Subscribe to different inputing topics
    rospy.Subscriber('/gazebo/model_states', ModelStates, callback)

    # Publish the filtered data to a topic
    pub = rospy.Publisher('/state_estimation/depth', Float64)
    rospy.spin()

if __name__ == '__main__':
    try:
        init()
    except rospy.ROSInterruptException:
        pass