#!/usr/bin/env python2.7

import rospy
from geometry_msgs.msg import PoseStamped
from gazebo_msgs.msg import ModelStates

time = None

def callback(modelStates):
    global time
    if time:
        if (rospy.get_time() - time) > 0.03:
            index = modelStates.name.index('robot')
            poseStamped = PoseStamped()
            poseStamped.pose = modelStates.pose[index]
            poseStamped.pose.position.x = 0
            poseStamped.pose.position.y = 0
            poseStamped.pose.position.z = 0
            pub.publish(poseStamped)
            time = rospy.get_time()
    else:
        time = rospy.get_time()

# Init the ros node, subscribers and publishers
# And run the node
def init():
    global pub
    rospy.init_node('sim_imu')

    # Subscribe to different inputing topics
    rospy.Subscriber('/gazebo/model_states', ModelStates, callback)

    # Publish the filtered data to a topic
    pub = rospy.Publisher('state_estimation/pose', PoseStamped)
    rospy.spin()
    
if __name__ == '__main__':
    try:
        init()
    except rospy.ROSInterruptException:
        pass