depth: '/state_estimation/filteredDepth'
battery_1_voltage: 'electrical_interface/batteryVoltage1'
battery_2_voltage: 'electrical_interface/batteryVoltage2'
front_camera_left: 'camera_front_left/image_rect/compressed'
front_camera_right: 'camera_front_right/image_rect/compressed'
down_camera: 'camera_down/image_rect/compressed'
processed_front_camera_left: 'front_cv/camera1/compressed'
processed_front_camera_right: 'front_cv/camera2/compressed'
processed_down_camera: 'down_cv/camera1/compressed'
cv_data_front: 'front_cv/data'
cv_data_down: 'down_cv/data'
planner_messages: 'planner/task'
cpu_temperature: 'status/temperature'
ubs_devices: 'status/usb'
state_estimation_pose: 'state_estimation/pose'
