image_feed/left: simulator/camera1/image_raw
image_feed/right: simulator/camera2/image_raw
camera_sensor_height: 0.04
camera_focal_length: 0.02
# Gate-related parameters:
gate_hue_range1_start: 125
gate_hue_range1_end: 179
gate_hue_range2_start: 0
gate_hue_range2_end: 20
gate_value_start: 55
gate_value_end: 200

################################################################################
# Line-related parameters:
################################################################################

# Range 1:
line_hue_range1_begin: 100
line_hue_range1_end: 180
line_sat_range1_begin: 30
line_sat_range1_end: 90
line_value_range1_begin: 170
line_value_range1_end: 250

# Range 2:
line_hue_range2_begin: 0
line_hue_range2_end: 180
line_sat_range2_begin: 20
line_sat_range2_end: 90
line_value_range2_begin: 160
line_value_range2_end: 240

# Range 3:
line_hue_range3_begin: 5
line_hue_range3_end: 15
line_sat_range3_begin: 70
line_sat_range3_end: 350
line_value_range3_begin: 30
line_value_range3_end: 180

# Range 4:
line_hue_range4_begin: 5
line_hue_range4_end: 150
line_sat_range4_begin: 20
line_sat_range4_end: 130
line_value_range4_begin: 30
line_value_range4_end: 180