#!/bin/bash

# DETERMINE SHELL
if [ $SHELL = "/bin/bash" ]; then
    extension='bash'
elif [ $SHELL = "/bin/sh" ]; then
    extension='sh'
elif [ $SHELL = "/bin/zsh" ]; then
    extension='zsh'
fi

# SOURCES
if [ -f /opt/ros/indigo/setup.$extension ];
then
    source /opt/ros/indigo/setup.$extension
else
    source /opt/ros/hydro/setup.$extension
fi
source $ROBOTIC_PATH/catkin_ws/devel/setup.$extension
source $ROBOTIC_PATH/setup/functionrc

# EXPORTS
if [ -f /opt/ros/indigo/setup.$extension ];
then
    export ROS_PACKAGE_PATH=/opt/ros/indigo/stacks:/opt/ros/indigo/share:$ROBOTIC_PATH/catkin_ws
else
    export ROS_PACKAGE_PATH=/opt/ros/hydro/stacks:/opt/ros/hydro/share:$ROBOTIC_PATH/catkin_ws
fi
export ROS_WORKSPACE=$ROBOTIC_PATH/catkin_ws

# ALIASES
alias asimosh='mosh robotics@10.0.0.1'
alias asimov='ssh -Y robotics@10.0.0.1'
alias asipull='$ROBOTIC_PATH/scripts/downloadBagsFromRobot.sh'
alias asipush='$ROBOTIC_PATH/scripts/uploadGitRepoToRobot.sh'
alias bag='$ROBOTIC_PATH/scripts/rosbagHelper.sh'
alias bag_merge='$ROBOTIC_PATH/scripts/mergeBags.py'
alias catkin_alert='catkin_make && blinky_alert'
alias controls='rostopic echo /controls/debug'
alias glances='glances -yet 5'
alias go='rosparam set /go 1'
alias ip_wlan="export ROS_IP=`ifconfig wlan0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`"
alias ip_eth="export ROS_IP=`ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`"
alias main='tmux attach -t MAIN'
alias softkill='rostopic pub -1 /controls/softKill std_msgs/Bool "data: true"'
alias softstart='rostopic pub -1 /controls/softKill std_msgs/Bool "data: false"'
alias uri="export ROS_MASTER_URI=http://10.0.0.1:11311"
alias watch_usb="watch --interval=2 --no-title \"lsusb | grep '16c0\\|0403\\|1e10\\|1d50' \""
