#!/bin/bash

# EXPORTS
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
TEAMOCIL_PATH=/home/robotics/McGill_RoboSub_2014/setup/

# START HERE
tmux new -d -x 185 -y 52 'teamocil startup'
