#!/bin/bash

# EXPORTS
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
TEAMOCIL_PATH=/home/robotics/McGill_RoboSub_2014/setup/

# START HERE
tmux new -d 'teamocil startup'
tmux move-window -s 2 -t 1
