# This custom message type is to be used to debug the controls
# It contains values published by controls that should be useful
# for debugging the control system

# Errors

VectorPID xError
VectorPID yError
VectorPID depthError
VectorPID pitchError
VectorPID yawError

# Gains

VectorPID xGain
VectorPID yGain
VectorPID depthGain
VectorPID pitchGain
VectorPID yawGain

# PID Forces (and Torques)

VectorPID xForce
VectorPID yForce
VectorPID depthForce
VectorPID pitchForce
VectorPID yawForce

# Total Forces?

# 

