# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../../UI/QT design/CompleteFinal.ui'
#
# Created: Sun Nov 24 20:47:29 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RoboticsMain(object):
    def setupUi(self, RoboticsMain):
        RoboticsMain.setObjectName(_fromUtf8("RoboticsMain"))
        RoboticsMain.resize(1683, 1017)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Only-Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RoboticsMain.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(RoboticsMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.VideoOuter = QtGui.QFrame(self.centralwidget)
        self.VideoOuter.setGeometry(QtCore.QRect(970, 200, 711, 761))
        self.VideoOuter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.VideoOuter.setFrameShadow(QtGui.QFrame.Raised)
        self.VideoOuter.setObjectName(_fromUtf8("VideoOuter"))
        self.preLeft = QtGui.QGraphicsView(self.VideoOuter)
        self.preLeft.setGeometry(QtCore.QRect(10, 10, 344, 241))
        self.preLeft.setMaximumSize(QtCore.QSize(344, 241))
        self.preLeft.setInteractive(False)
        self.preLeft.setObjectName(_fromUtf8("preLeft"))
        self.preRight = QtGui.QGraphicsView(self.VideoOuter)
        self.preRight.setGeometry(QtCore.QRect(360, 10, 344, 241))
        self.preRight.setMaximumSize(QtCore.QSize(344, 241))
        self.preRight.setInteractive(False)
        self.preRight.setObjectName(_fromUtf8("preRight"))
        self.postLeft = QtGui.QGraphicsView(self.VideoOuter)
        self.postLeft.setGeometry(QtCore.QRect(10, 260, 344, 241))
        self.postLeft.setMaximumSize(QtCore.QSize(344, 241))
        self.postLeft.setInteractive(False)
        self.postLeft.setObjectName(_fromUtf8("postLeft"))
        self.postRight = QtGui.QGraphicsView(self.VideoOuter)
        self.postRight.setGeometry(QtCore.QRect(360, 260, 344, 241))
        self.postRight.setMaximumSize(QtCore.QSize(344, 241))
        self.postRight.setInteractive(False)
        self.postRight.setObjectName(_fromUtf8("postRight"))
        self.preBottom = QtGui.QGraphicsView(self.VideoOuter)
        self.preBottom.setGeometry(QtCore.QRect(10, 510, 344, 241))
        self.preBottom.setMaximumSize(QtCore.QSize(344, 241))
        self.preBottom.setInteractive(False)
        self.preBottom.setObjectName(_fromUtf8("preBottom"))
        self.postBottom = QtGui.QGraphicsView(self.VideoOuter)
        self.postBottom.setGeometry(QtCore.QRect(360, 510, 344, 241))
        self.postBottom.setMaximumSize(QtCore.QSize(344, 241))
        self.postBottom.setInteractive(False)
        self.postBottom.setObjectName(_fromUtf8("postBottom"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 351, 131))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Landscape-Logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.StatusBar = QtGui.QFrame(self.centralwidget)
        self.StatusBar.setGeometry(QtCore.QRect(370, 10, 1311, 181))
        self.StatusBar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.StatusBar.setFrameShadow(QtGui.QFrame.Raised)
        self.StatusBar.setObjectName(_fromUtf8("StatusBar"))
        self.label_2 = QtGui.QLabel(self.StatusBar)
        self.label_2.setGeometry(QtCore.QRect(560, 50, 151, 91))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/cg_playstation_3_controller_2.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.manualControl = QtGui.QRadioButton(self.StatusBar)
        self.manualControl.setGeometry(QtCore.QRect(730, 40, 141, 22))
        self.manualControl.setChecked(True)
        self.manualControl.setObjectName(_fromUtf8("manualControl"))
        self.autonomousControl = QtGui.QRadioButton(self.StatusBar)
        self.autonomousControl.setGeometry(QtCore.QRect(730, 60, 161, 22))
        self.autonomousControl.setObjectName(_fromUtf8("autonomousControl"))
        self.Battery = QtGui.QProgressBar(self.StatusBar)
        self.Battery.setGeometry(QtCore.QRect(910, 60, 141, 101))
        self.Battery.setProperty("value", 24)
        self.Battery.setObjectName(_fromUtf8("Battery"))
        self.label_3 = QtGui.QLabel(self.StatusBar)
        self.label_3.setGeometry(QtCore.QRect(670, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.StatusBar)
        self.label_4.setGeometry(QtCore.QRect(940, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line = QtGui.QFrame(self.StatusBar)
        self.line.setGeometry(QtCore.QRect(890, 10, 20, 161))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.StatusBar)
        self.line_2.setGeometry(QtCore.QRect(1050, 10, 20, 161))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.attemptPS3 = QtGui.QPushButton(self.StatusBar)
        self.attemptPS3.setGeometry(QtCore.QRect(730, 90, 161, 27))
        self.attemptPS3.setObjectName(_fromUtf8("attemptPS3"))
        self.label_5 = QtGui.QLabel(self.StatusBar)
        self.label_5.setGeometry(QtCore.QRect(720, 140, 121, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.colourStatus = QtGui.QLabel(self.StatusBar)
        self.colourStatus.setGeometry(QtCore.QRect(850, 130, 41, 41))
        self.colourStatus.setText(_fromUtf8(""))
        self.colourStatus.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/red.jpg")))
        self.colourStatus.setObjectName(_fromUtf8("colourStatus"))
        self.label_6 = QtGui.QLabel(self.StatusBar)
        self.label_6.setGeometry(QtCore.QRect(1170, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.stateData = QtGui.QLabel(self.StatusBar)
        self.stateData.setGeometry(QtCore.QRect(1070, 56, 231, 111))
        self.stateData.setAlignment(QtCore.Qt.AlignCenter)
        self.stateData.setObjectName(_fromUtf8("stateData"))
        self.line_3 = QtGui.QFrame(self.StatusBar)
        self.line_3.setGeometry(QtCore.QRect(530, 10, 20, 161))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.StatusBar)
        self.line_4.setGeometry(QtCore.QRect(270, 10, 20, 161))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_7 = QtGui.QLabel(self.StatusBar)
        self.label_7.setGeometry(QtCore.QRect(370, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.StatusBar)
        self.label_8.setGeometry(QtCore.QRect(100, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.angularHorizantal = QtGui.QSlider(self.StatusBar)
        self.angularHorizantal.setGeometry(QtCore.QRect(300, 150, 191, 18))
        self.angularHorizantal.setMinimum(-99)
        self.angularHorizantal.setOrientation(QtCore.Qt.Horizontal)
        self.angularHorizantal.setObjectName(_fromUtf8("angularHorizantal"))
        self.linearHorizantal = QtGui.QSlider(self.StatusBar)
        self.linearHorizantal.setGeometry(QtCore.QRect(20, 150, 201, 20))
        self.linearHorizantal.setMinimum(-99)
        self.linearHorizantal.setOrientation(QtCore.Qt.Horizontal)
        self.linearHorizantal.setObjectName(_fromUtf8("linearHorizantal"))
        self.linearVertical = QtGui.QSlider(self.StatusBar)
        self.linearVertical.setGeometry(QtCore.QRect(240, 10, 18, 160))
        self.linearVertical.setMinimum(-99)
        self.linearVertical.setOrientation(QtCore.Qt.Vertical)
        self.linearVertical.setObjectName(_fromUtf8("linearVertical"))
        self.angularVertical = QtGui.QSlider(self.StatusBar)
        self.angularVertical.setGeometry(QtCore.QRect(510, 10, 18, 160))
        self.angularVertical.setMinimum(-99)
        self.angularVertical.setOrientation(QtCore.Qt.Vertical)
        self.angularVertical.setObjectName(_fromUtf8("angularVertical"))
        self.label_14 = QtGui.QLabel(self.StatusBar)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 16, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.StatusBar)
        self.label_15.setGeometry(QtCore.QRect(20, 90, 16, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.linearX = QtGui.QTextEdit(self.StatusBar)
        self.linearX.setGeometry(QtCore.QRect(50, 60, 171, 21))
        self.linearX.setReadOnly(True)
        self.linearX.setObjectName(_fromUtf8("linearX"))
        self.linearY = QtGui.QTextEdit(self.StatusBar)
        self.linearY.setGeometry(QtCore.QRect(50, 90, 171, 21))
        self.linearY.setReadOnly(True)
        self.linearY.setObjectName(_fromUtf8("linearY"))
        self.label_18 = QtGui.QLabel(self.StatusBar)
        self.label_18.setGeometry(QtCore.QRect(20, 120, 16, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.linearZ = QtGui.QTextEdit(self.StatusBar)
        self.linearZ.setGeometry(QtCore.QRect(50, 120, 171, 21))
        self.linearZ.setReadOnly(True)
        self.linearZ.setObjectName(_fromUtf8("linearZ"))
        self.label_16 = QtGui.QLabel(self.StatusBar)
        self.label_16.setGeometry(QtCore.QRect(300, 90, 16, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.angularZ = QtGui.QTextEdit(self.StatusBar)
        self.angularZ.setGeometry(QtCore.QRect(330, 120, 171, 21))
        self.angularZ.setReadOnly(True)
        self.angularZ.setObjectName(_fromUtf8("angularZ"))
        self.label_17 = QtGui.QLabel(self.StatusBar)
        self.label_17.setGeometry(QtCore.QRect(300, 60, 16, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_19 = QtGui.QLabel(self.StatusBar)
        self.label_19.setGeometry(QtCore.QRect(300, 120, 16, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.angularY = QtGui.QTextEdit(self.StatusBar)
        self.angularY.setGeometry(QtCore.QRect(330, 90, 171, 21))
        self.angularY.setReadOnly(True)
        self.angularY.setObjectName(_fromUtf8("angularY"))
        self.angularX = QtGui.QTextEdit(self.StatusBar)
        self.angularX.setGeometry(QtCore.QRect(330, 60, 171, 21))
        self.angularX.setReadOnly(True)
        self.angularX.setObjectName(_fromUtf8("angularX"))
        self.logObject = QtGui.QTextEdit(self.centralwidget)
        self.logObject.setGeometry(QtCore.QRect(420, 700, 551, 261))
        self.logObject.setReadOnly(True)
        self.logObject.setObjectName(_fromUtf8("logObject"))
        self.IMUraws = QtGui.QFrame(self.centralwidget)
        self.IMUraws.setGeometry(QtCore.QRect(9, 199, 401, 761))
        self.IMUraws.setFrameShape(QtGui.QFrame.StyledPanel)
        self.IMUraws.setFrameShadow(QtGui.QFrame.Raised)
        self.IMUraws.setObjectName(_fromUtf8("IMUraws"))
        self.label_9 = QtGui.QLabel(self.IMUraws)
        self.label_9.setGeometry(QtCore.QRect(50, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.imugraphics = GraphicsLayoutWidget(self.IMUraws)
        self.imugraphics.setGeometry(QtCore.QRect(0, 40, 401, 721))
        self.imugraphics.setObjectName(_fromUtf8("imugraphics"))
        self.DVLFrame = QtGui.QFrame(self.centralwidget)
        self.DVLFrame.setGeometry(QtCore.QRect(420, 540, 550, 151))
        self.DVLFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DVLFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.DVLFrame.setObjectName(_fromUtf8("DVLFrame"))
        self.label_13 = QtGui.QLabel(self.DVLFrame)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_20 = QtGui.QLabel(self.DVLFrame)
        self.label_20.setGeometry(QtCore.QRect(160, 80, 16, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.DVLFrame)
        self.label_21.setGeometry(QtCore.QRect(160, 50, 16, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.dvlLinearZ = QtGui.QTextEdit(self.DVLFrame)
        self.dvlLinearZ.setGeometry(QtCore.QRect(180, 110, 81, 21))
        self.dvlLinearZ.setReadOnly(True)
        self.dvlLinearZ.setObjectName(_fromUtf8("dvlLinearZ"))
        self.dvlLinearX = QtGui.QTextEdit(self.DVLFrame)
        self.dvlLinearX.setGeometry(QtCore.QRect(180, 50, 81, 21))
        self.dvlLinearX.setReadOnly(True)
        self.dvlLinearX.setObjectName(_fromUtf8("dvlLinearX"))
        self.label_22 = QtGui.QLabel(self.DVLFrame)
        self.label_22.setGeometry(QtCore.QRect(160, 110, 16, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.dvlLinearY = QtGui.QTextEdit(self.DVLFrame)
        self.dvlLinearY.setGeometry(QtCore.QRect(180, 80, 81, 21))
        self.dvlLinearY.setReadOnly(True)
        self.dvlLinearY.setObjectName(_fromUtf8("dvlLinearY"))
        self.label_23 = QtGui.QLabel(self.DVLFrame)
        self.label_23.setGeometry(QtCore.QRect(430, 50, 16, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.DVLFrame)
        self.label_24.setGeometry(QtCore.QRect(430, 110, 16, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.dvlAngularX = QtGui.QTextEdit(self.DVLFrame)
        self.dvlAngularX.setGeometry(QtCore.QRect(460, 50, 81, 21))
        self.dvlAngularX.setReadOnly(True)
        self.dvlAngularX.setObjectName(_fromUtf8("dvlAngularX"))
        self.dvlAngularZ = QtGui.QTextEdit(self.DVLFrame)
        self.dvlAngularZ.setGeometry(QtCore.QRect(460, 110, 81, 21))
        self.dvlAngularZ.setReadOnly(True)
        self.dvlAngularZ.setObjectName(_fromUtf8("dvlAngularZ"))
        self.label_25 = QtGui.QLabel(self.DVLFrame)
        self.label_25.setGeometry(QtCore.QRect(430, 80, 16, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.dvlAngularY = QtGui.QTextEdit(self.DVLFrame)
        self.dvlAngularY.setGeometry(QtCore.QRect(460, 80, 81, 21))
        self.dvlAngularY.setReadOnly(True)
        self.dvlAngularY.setObjectName(_fromUtf8("dvlAngularY"))
        self.label_26 = QtGui.QLabel(self.DVLFrame)
        self.label_26.setGeometry(QtCore.QRect(120, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.DVLFrame)
        self.label_27.setGeometry(QtCore.QRect(400, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.dvlLinear = QtGui.QGraphicsView(self.DVLFrame)
        self.dvlLinear.setGeometry(QtCore.QRect(0, 40, 161, 111))
        self.dvlLinear.setObjectName(_fromUtf8("dvlLinear"))
        self.dvlAngular = QtGui.QGraphicsView(self.DVLFrame)
        self.dvlAngular.setGeometry(QtCore.QRect(270, 40, 161, 111))
        self.dvlAngular.setObjectName(_fromUtf8("dvlAngular"))
        self.IMUdirectional = QtGui.QFrame(self.centralwidget)
        self.IMUdirectional.setGeometry(QtCore.QRect(420, 380, 550, 151))
        self.IMUdirectional.setFrameShape(QtGui.QFrame.StyledPanel)
        self.IMUdirectional.setFrameShadow(QtGui.QFrame.Raised)
        self.IMUdirectional.setObjectName(_fromUtf8("IMUdirectional"))
        self.label_12 = QtGui.QLabel(self.IMUdirectional)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.Depth = QtGui.QFrame(self.centralwidget)
        self.Depth.setGeometry(QtCore.QRect(420, 200, 270, 171))
        self.Depth.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Depth.setFrameShadow(QtGui.QFrame.Raised)
        self.Depth.setObjectName(_fromUtf8("Depth"))
        self.label_10 = QtGui.QLabel(self.Depth)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.depth = GraphicsLayoutWidget(self.Depth)
        self.depth.setGeometry(QtCore.QRect(0, 30, 271, 141))
        self.depth.setObjectName(_fromUtf8("depth"))
        self.Pressure = QtGui.QFrame(self.centralwidget)
        self.Pressure.setGeometry(QtCore.QRect(700, 200, 270, 171))
        self.Pressure.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Pressure.setFrameShadow(QtGui.QFrame.Raised)
        self.Pressure.setObjectName(_fromUtf8("Pressure"))
        self.label_11 = QtGui.QLabel(self.Pressure)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pressure = GraphicsLayoutWidget(self.Pressure)
        self.pressure.setGeometry(QtCore.QRect(0, 30, 271, 141))
        self.pressure.setObjectName(_fromUtf8("pressure"))
        RoboticsMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RoboticsMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1683, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        RoboticsMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RoboticsMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RoboticsMain.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(RoboticsMain)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(RoboticsMain)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), RoboticsMain.close)
        QtCore.QMetaObject.connectSlotsByName(RoboticsMain)

    def retranslateUi(self, RoboticsMain):
        RoboticsMain.setWindowTitle(QtGui.QApplication.translate("RoboticsMain", "Robotics Diagnostics and Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.manualControl.setText(QtGui.QApplication.translate("RoboticsMain", "Manual Control", None, QtGui.QApplication.UnicodeUTF8))
        self.autonomousControl.setText(QtGui.QApplication.translate("RoboticsMain", "Autonomous Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RoboticsMain", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RoboticsMain", "Battery", None, QtGui.QApplication.UnicodeUTF8))
        self.attemptPS3.setText(QtGui.QApplication.translate("RoboticsMain", "Connect PS3 Contoller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RoboticsMain", "Controller Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RoboticsMain", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.stateData.setText(QtGui.QApplication.translate("RoboticsMain", "No State Data Recieved", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RoboticsMain", "Angular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RoboticsMain", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RoboticsMain", "IMU Raw Readings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("RoboticsMain", "DVL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("RoboticsMain", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("RoboticsMain", "Angular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RoboticsMain", "IMU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("RoboticsMain", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RoboticsMain", "Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RoboticsMain", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("RoboticsMain", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("RoboticsMain", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import GraphicsLayoutWidget
import FinalRobotics_rc
