# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'no_imu_gr_resizable_TAB.ui'
#
# Created: Wed Apr 30 13:58:11 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RoboticsMain(object):
    def setupUi(self, RoboticsMain):
        RoboticsMain.setObjectName(_fromUtf8("RoboticsMain"))
        RoboticsMain.resize(1065, 976)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Only-Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RoboticsMain.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(RoboticsMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 151))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(282, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout.addWidget(self.label_22)
        self.label_26 = QtGui.QLabel(self.frame_2)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout.addWidget(self.label_26)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.front_x = QtGui.QLineEdit(self.frame_2)
        self.front_x.setMaximumSize(QtCore.QSize(16777215, 27))
        self.front_x.setReadOnly(True)
        self.front_x.setObjectName(_fromUtf8("front_x"))
        self.gridLayout.addWidget(self.front_x, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame_2)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 0, 2, 1, 1)
        self.front_pitch = QtGui.QLineEdit(self.frame_2)
        self.front_pitch.setMaximumSize(QtCore.QSize(16777215, 27))
        self.front_pitch.setReadOnly(True)
        self.front_pitch.setObjectName(_fromUtf8("front_pitch"))
        self.gridLayout.addWidget(self.front_pitch, 0, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.frame_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 0, 4, 1, 1)
        self.down_x = QtGui.QLineEdit(self.frame_2)
        self.down_x.setMaximumSize(QtCore.QSize(16777215, 27))
        self.down_x.setReadOnly(True)
        self.down_x.setObjectName(_fromUtf8("down_x"))
        self.gridLayout.addWidget(self.down_x, 0, 5, 1, 1)
        self.label_28 = QtGui.QLabel(self.frame_2)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 0, 6, 1, 1)
        self.down_pitch = QtGui.QLineEdit(self.frame_2)
        self.down_pitch.setMaximumSize(QtCore.QSize(16777215, 27))
        self.down_pitch.setReadOnly(True)
        self.down_pitch.setObjectName(_fromUtf8("down_pitch"))
        self.gridLayout.addWidget(self.down_pitch, 0, 7, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.front_y = QtGui.QLineEdit(self.frame_2)
        self.front_y.setMaximumSize(QtCore.QSize(16777215, 27))
        self.front_y.setReadOnly(True)
        self.front_y.setObjectName(_fromUtf8("front_y"))
        self.gridLayout.addWidget(self.front_y, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame_2)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 1, 2, 1, 1)
        self.front_yaw = QtGui.QLineEdit(self.frame_2)
        self.front_yaw.setMaximumSize(QtCore.QSize(16777215, 27))
        self.front_yaw.setReadOnly(True)
        self.front_yaw.setObjectName(_fromUtf8("front_yaw"))
        self.gridLayout.addWidget(self.front_yaw, 1, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.frame_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 1, 4, 1, 1)
        self.down_y = QtGui.QLineEdit(self.frame_2)
        self.down_y.setMaximumSize(QtCore.QSize(16777215, 27))
        self.down_y.setReadOnly(True)
        self.down_y.setObjectName(_fromUtf8("down_y"))
        self.gridLayout.addWidget(self.down_y, 1, 5, 1, 1)
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 1, 6, 1, 1)
        self.down_aw = QtGui.QLineEdit(self.frame_2)
        self.down_aw.setMaximumSize(QtCore.QSize(16777215, 27))
        self.down_aw.setReadOnly(True)
        self.down_aw.setObjectName(_fromUtf8("down_aw"))
        self.gridLayout.addWidget(self.down_aw, 1, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.front_z = QtGui.QLineEdit(self.frame_2)
        self.front_z.setMaximumSize(QtCore.QSize(16777215, 27))
        self.front_z.setReadOnly(True)
        self.front_z.setObjectName(_fromUtf8("front_z"))
        self.gridLayout.addWidget(self.front_z, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.front_objType = QtGui.QLineEdit(self.frame_2)
        self.front_objType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.front_objType.setReadOnly(True)
        self.front_objType.setObjectName(_fromUtf8("front_objType"))
        self.gridLayout.addWidget(self.front_objType, 2, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.frame_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 2, 4, 1, 1)
        self.down_z = QtGui.QLineEdit(self.frame_2)
        self.down_z.setMaximumSize(QtCore.QSize(16777215, 27))
        self.down_z.setReadOnly(True)
        self.down_z.setObjectName(_fromUtf8("down_z"))
        self.gridLayout.addWidget(self.down_z, 2, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.frame_2)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 2, 6, 1, 1)
        self.down_objType = QtGui.QLineEdit(self.frame_2)
        self.down_objType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.down_objType.setReadOnly(True)
        self.down_objType.setObjectName(_fromUtf8("down_objType"))
        self.gridLayout.addWidget(self.down_objType, 2, 7, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_3.addWidget(self.line_2)
        self.linear_cmd_vel = QtGui.QGridLayout()
        self.linear_cmd_vel.setObjectName(_fromUtf8("linear_cmd_vel"))
        self.linearHorizantal = QtGui.QSlider(self.frame_2)
        self.linearHorizantal.setOrientation(QtCore.Qt.Horizontal)
        self.linearHorizantal.setObjectName(_fromUtf8("linearHorizantal"))
        self.linear_cmd_vel.addWidget(self.linearHorizantal, 2, 0, 1, 1)
        self.linearVertical = QtGui.QSlider(self.frame_2)
        self.linearVertical.setOrientation(QtCore.Qt.Vertical)
        self.linearVertical.setObjectName(_fromUtf8("linearVertical"))
        self.linear_cmd_vel.addWidget(self.linearVertical, 1, 1, 2, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.linearX = QtGui.QLineEdit(self.frame_2)
        self.linearX.setReadOnly(True)
        self.linearX.setObjectName(_fromUtf8("linearX"))
        self.gridLayout_2.addWidget(self.linearX, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.linearY = QtGui.QLineEdit(self.frame_2)
        self.linearY.setReadOnly(True)
        self.linearY.setObjectName(_fromUtf8("linearY"))
        self.gridLayout_2.addWidget(self.linearY, 1, 1, 1, 1)
        self.linearZ = QtGui.QLineEdit(self.frame_2)
        self.linearZ.setReadOnly(True)
        self.linearZ.setObjectName(_fromUtf8("linearZ"))
        self.gridLayout_2.addWidget(self.linearZ, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.linear_cmd_vel.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.linear_cmd_vel.addWidget(self.label_17, 0, 0, 1, 1)
        self.linear_cmd_vel.setColumnStretch(0, 1)
        self.linear_cmd_vel.setColumnStretch(1, 1)
        self.linear_cmd_vel.setRowStretch(0, 1)
        self.linear_cmd_vel.setRowStretch(1, 3)
        self.linear_cmd_vel.setRowStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.linear_cmd_vel)
        self.angularcmd_vel = QtGui.QGridLayout()
        self.angularcmd_vel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.angularcmd_vel.setObjectName(_fromUtf8("angularcmd_vel"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.angularX = QtGui.QLineEdit(self.frame_2)
        self.angularX.setReadOnly(True)
        self.angularX.setObjectName(_fromUtf8("angularX"))
        self.gridLayout_5.addWidget(self.angularX, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.angularY = QtGui.QLineEdit(self.frame_2)
        self.angularY.setReadOnly(True)
        self.angularY.setObjectName(_fromUtf8("angularY"))
        self.gridLayout_5.addWidget(self.angularY, 1, 1, 1, 1)
        self.angularZ = QtGui.QLineEdit(self.frame_2)
        self.angularZ.setReadOnly(True)
        self.angularZ.setObjectName(_fromUtf8("angularZ"))
        self.gridLayout_5.addWidget(self.angularZ, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 2, 0, 1, 1)
        self.angularcmd_vel.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.angularHorizantal = QtGui.QSlider(self.frame_2)
        self.angularHorizantal.setOrientation(QtCore.Qt.Horizontal)
        self.angularHorizantal.setObjectName(_fromUtf8("angularHorizantal"))
        self.angularcmd_vel.addWidget(self.angularHorizantal, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.angularcmd_vel.addWidget(self.label_18, 0, 0, 1, 1)
        self.angularVertical = QtGui.QSlider(self.frame_2)
        self.angularVertical.setOrientation(QtCore.Qt.Vertical)
        self.angularVertical.setObjectName(_fromUtf8("angularVertical"))
        self.angularcmd_vel.addWidget(self.angularVertical, 1, 1, 2, 1)
        self.angularcmd_vel.setRowStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.angularcmd_vel)
        self.controller_select = QtGui.QVBoxLayout()
        self.controller_select.setObjectName(_fromUtf8("controller_select"))
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setMinimumSize(QtCore.QSize(115, 0))
        self.label_19.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.controller_select.addWidget(self.label_19)
        self.keyboardControl = QtGui.QRadioButton(self.frame_2)
        self.keyboardControl.setMinimumSize(QtCore.QSize(115, 0))
        self.keyboardControl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.keyboardControl.setObjectName(_fromUtf8("keyboardControl"))
        self.controller_select.addWidget(self.keyboardControl)
        self.manualControl = QtGui.QRadioButton(self.frame_2)
        self.manualControl.setMinimumSize(QtCore.QSize(115, 0))
        self.manualControl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.manualControl.setObjectName(_fromUtf8("manualControl"))
        self.controller_select.addWidget(self.manualControl)
        self.autonomousControl = QtGui.QRadioButton(self.frame_2)
        self.autonomousControl.setMinimumSize(QtCore.QSize(115, 0))
        self.autonomousControl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.autonomousControl.setObjectName(_fromUtf8("autonomousControl"))
        self.controller_select.addWidget(self.autonomousControl)
        self.attemptPS3 = QtGui.QPushButton(self.frame_2)
        self.attemptPS3.setMinimumSize(QtCore.QSize(115, 0))
        self.attemptPS3.setMaximumSize(QtCore.QSize(115, 16777215))
        self.attemptPS3.setObjectName(_fromUtf8("attemptPS3"))
        self.controller_select.addWidget(self.attemptPS3)
        self.horizontalLayout_3.addLayout(self.controller_select)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vid_array = QtGui.QGridLayout()
        self.vid_array.setSpacing(2)
        self.vid_array.setObjectName(_fromUtf8("vid_array"))
        self.preLeft = QtGui.QLabel(self.tab)
        self.preLeft.setMinimumSize(QtCore.QSize(250, 230))
        self.preLeft.setMaximumSize(QtCore.QSize(500, 450))
        self.preLeft.setFrameShape(QtGui.QFrame.Box)
        self.preLeft.setScaledContents(True)
        self.preLeft.setObjectName(_fromUtf8("preLeft"))
        self.vid_array.addWidget(self.preLeft, 0, 0, 1, 1)
        self.preRight = QtGui.QLabel(self.tab)
        self.preRight.setMinimumSize(QtCore.QSize(250, 230))
        self.preRight.setMaximumSize(QtCore.QSize(500, 450))
        self.preRight.setFrameShape(QtGui.QFrame.Box)
        self.preRight.setScaledContents(True)
        self.preRight.setObjectName(_fromUtf8("preRight"))
        self.vid_array.addWidget(self.preRight, 1, 0, 1, 1)
        self.postLeft = QtGui.QLabel(self.tab)
        self.postLeft.setMinimumSize(QtCore.QSize(250, 230))
        self.postLeft.setMaximumSize(QtCore.QSize(500, 450))
        self.postLeft.setFrameShape(QtGui.QFrame.Box)
        self.postLeft.setScaledContents(True)
        self.postLeft.setObjectName(_fromUtf8("postLeft"))
        self.vid_array.addWidget(self.postLeft, 0, 1, 1, 1)
        self.preBottom = QtGui.QLabel(self.tab)
        self.preBottom.setMinimumSize(QtCore.QSize(250, 230))
        self.preBottom.setMaximumSize(QtCore.QSize(500, 450))
        self.preBottom.setFrameShape(QtGui.QFrame.Box)
        self.preBottom.setScaledContents(True)
        self.preBottom.setObjectName(_fromUtf8("preBottom"))
        self.vid_array.addWidget(self.preBottom, 2, 0, 1, 1)
        self.postRight = QtGui.QLabel(self.tab)
        self.postRight.setMinimumSize(QtCore.QSize(250, 230))
        self.postRight.setMaximumSize(QtCore.QSize(500, 450))
        self.postRight.setFrameShape(QtGui.QFrame.Box)
        self.postRight.setScaledContents(True)
        self.postRight.setObjectName(_fromUtf8("postRight"))
        self.vid_array.addWidget(self.postRight, 1, 1, 1, 1)
        self.posBottom = QtGui.QLabel(self.tab)
        self.posBottom.setMinimumSize(QtCore.QSize(250, 230))
        self.posBottom.setMaximumSize(QtCore.QSize(500, 450))
        self.posBottom.setFrameShape(QtGui.QFrame.Box)
        self.posBottom.setScaledContents(True)
        self.posBottom.setObjectName(_fromUtf8("posBottom"))
        self.vid_array.addWidget(self.posBottom, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.vid_array)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_2.addWidget(self.label_30)
        self.logObject = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logObject.sizePolicy().hasHeightForWidth())
        self.logObject.setSizePolicy(sizePolicy)
        self.logObject.setMinimumSize(QtCore.QSize(210, 0))
        self.logObject.setMaximumSize(QtCore.QSize(1220223, 12312312))
        self.logObject.setReadOnly(True)
        self.logObject.setObjectName(_fromUtf8("logObject"))
        self.verticalLayout_2.addWidget(self.logObject)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.imugraphics = GraphicsLayoutWidget(self.tab)
        self.imugraphics.setEnabled(True)
        self.imugraphics.setMinimumSize(QtCore.QSize(0, 0))
        self.imugraphics.setMaximumSize(QtCore.QSize(1920, 980))
        self.imugraphics.setObjectName(_fromUtf8("imugraphics"))
        self.horizontalLayout_4.addWidget(self.imugraphics)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.temp_core1 = QtGui.QLabel(self.tab)
        self.temp_core1.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_core1.setObjectName(_fromUtf8("temp_core1"))
        self.gridLayout_14.addWidget(self.temp_core1, 1, 0, 1, 1)
        self.temp_core3 = QtGui.QLabel(self.tab)
        self.temp_core3.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_core3.setObjectName(_fromUtf8("temp_core3"))
        self.gridLayout_14.addWidget(self.temp_core3, 1, 2, 1, 1)
        self.temp_core4 = QtGui.QLabel(self.tab)
        self.temp_core4.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_core4.setObjectName(_fromUtf8("temp_core4"))
        self.gridLayout_14.addWidget(self.temp_core4, 1, 3, 1, 1)
        self.label_56 = QtGui.QLabel(self.tab)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_14.addWidget(self.label_56, 0, 0, 1, 1)
        self.label_58 = QtGui.QLabel(self.tab)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_14.addWidget(self.label_58, 0, 3, 1, 1)
        self.label_60 = QtGui.QLabel(self.tab)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_14.addWidget(self.label_60, 0, 2, 1, 1)
        self.label_62 = QtGui.QLabel(self.tab)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_14.addWidget(self.label_62, 0, 1, 1, 1)
        self.temp_core2 = QtGui.QLabel(self.tab)
        self.temp_core2.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_core2.setObjectName(_fromUtf8("temp_core2"))
        self.gridLayout_14.addWidget(self.temp_core2, 1, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.tab)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_14.addWidget(self.label_55, 0, 4, 1, 1)
        self.hdd_temp_lbl = QtGui.QLabel(self.tab)
        self.hdd_temp_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.hdd_temp_lbl.setObjectName(_fromUtf8("hdd_temp_lbl"))
        self.gridLayout_14.addWidget(self.hdd_temp_lbl, 1, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_14)
        self.line_5 = QtGui.QFrame(self.tab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_4.addWidget(self.line_5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_6.addWidget(self.label_31, 0, 1, 1, 1)
        self.bat_lbl = QtGui.QLabel(self.tab)
        self.bat_lbl.setMinimumSize(QtCore.QSize(0, 17))
        self.bat_lbl.setMaximumSize(QtCore.QSize(110, 17))
        self.bat_lbl.setObjectName(_fromUtf8("bat_lbl"))
        self.gridLayout_6.addWidget(self.bat_lbl, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_6.addWidget(self.label_32, 0, 3, 1, 1)
        self.usb_lbl = QtGui.QLabel(self.tab)
        self.usb_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.usb_lbl.setObjectName(_fromUtf8("usb_lbl"))
        self.gridLayout_6.addWidget(self.usb_lbl, 1, 0, 1, 1)
        self.ambiant_temp_lbl = QtGui.QLabel(self.tab)
        self.ambiant_temp_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ambiant_temp_lbl.setObjectName(_fromUtf8("ambiant_temp_lbl"))
        self.gridLayout_6.addWidget(self.ambiant_temp_lbl, 1, 1, 1, 1)
        self.bat1_lbl = QtGui.QLabel(self.tab)
        self.bat1_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bat1_lbl.setObjectName(_fromUtf8("bat1_lbl"))
        self.gridLayout_6.addWidget(self.bat1_lbl, 1, 3, 1, 1)
        self.bat2_lbl = QtGui.QLabel(self.tab)
        self.bat2_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bat2_lbl.setObjectName(_fromUtf8("bat2_lbl"))
        self.gridLayout_6.addWidget(self.bat2_lbl, 1, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(419, 292))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.poseVizFrame = QtGui.QVBoxLayout()
        self.poseVizFrame.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.poseVizFrame.setObjectName(_fromUtf8("poseVizFrame"))
        self.gridLayout_8.addLayout(self.poseVizFrame, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_7.addWidget(self.label_33)
        self.ps3_present = QtGui.QCheckBox(self.tab_2)
        self.ps3_present.setCheckable(True)
        self.ps3_present.setTristate(False)
        self.ps3_present.setObjectName(_fromUtf8("ps3_present"))
        self.verticalLayout_7.addWidget(self.ps3_present)
        self.thruster_stop = QtGui.QCheckBox(self.tab_2)
        self.thruster_stop.setCheckable(True)
        self.thruster_stop.setObjectName(_fromUtf8("thruster_stop"))
        self.verticalLayout_7.addWidget(self.thruster_stop)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.fiel_thruster_3 = QtGui.QSpinBox(self.tab_2)
        self.fiel_thruster_3.setEnabled(True)
        self.fiel_thruster_3.setReadOnly(True)
        self.fiel_thruster_3.setMinimum(-500)
        self.fiel_thruster_3.setMaximum(500)
        self.fiel_thruster_3.setObjectName(_fromUtf8("fiel_thruster_3"))
        self.gridLayout_9.addWidget(self.fiel_thruster_3, 3, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setEnabled(False)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_9.addWidget(self.label_34, 1, 0, 1, 1)
        self.fiel_thruster_2 = QtGui.QSpinBox(self.tab_2)
        self.fiel_thruster_2.setEnabled(True)
        self.fiel_thruster_2.setReadOnly(True)
        self.fiel_thruster_2.setMinimum(-500)
        self.fiel_thruster_2.setMaximum(500)
        self.fiel_thruster_2.setObjectName(_fromUtf8("fiel_thruster_2"))
        self.gridLayout_9.addWidget(self.fiel_thruster_2, 2, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_2)
        self.label_35.setEnabled(False)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_9.addWidget(self.label_35, 2, 0, 1, 1)
        self.fiel_thruster_5 = QtGui.QSpinBox(self.tab_2)
        self.fiel_thruster_5.setEnabled(True)
        self.fiel_thruster_5.setReadOnly(True)
        self.fiel_thruster_5.setMinimum(-500)
        self.fiel_thruster_5.setMaximum(500)
        self.fiel_thruster_5.setObjectName(_fromUtf8("fiel_thruster_5"))
        self.gridLayout_9.addWidget(self.fiel_thruster_5, 5, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.tab_2)
        self.label_36.setEnabled(False)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_9.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setEnabled(False)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_9.addWidget(self.label_37, 6, 0, 1, 1)
        self.fiel_thruster_4 = QtGui.QSpinBox(self.tab_2)
        self.fiel_thruster_4.setEnabled(True)
        self.fiel_thruster_4.setReadOnly(True)
        self.fiel_thruster_4.setMinimum(-500)
        self.fiel_thruster_4.setMaximum(500)
        self.fiel_thruster_4.setObjectName(_fromUtf8("fiel_thruster_4"))
        self.gridLayout_9.addWidget(self.fiel_thruster_4, 4, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_2)
        self.label_38.setEnabled(False)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_9.addWidget(self.label_38, 5, 0, 1, 1)
        self.fiel_thruster_6 = QtGui.QSpinBox(self.tab_2)
        self.fiel_thruster_6.setEnabled(True)
        self.fiel_thruster_6.setReadOnly(True)
        self.fiel_thruster_6.setMinimum(-500)
        self.fiel_thruster_6.setMaximum(500)
        self.fiel_thruster_6.setObjectName(_fromUtf8("fiel_thruster_6"))
        self.gridLayout_9.addWidget(self.fiel_thruster_6, 6, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.tab_2)
        self.label_39.setEnabled(False)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_9.addWidget(self.label_39, 4, 0, 1, 1)
        self.fiel_thruste_1 = QtGui.QSpinBox(self.tab_2)
        self.fiel_thruste_1.setEnabled(True)
        self.fiel_thruste_1.setReadOnly(True)
        self.fiel_thruste_1.setMinimum(-500)
        self.fiel_thruste_1.setMaximum(500)
        self.fiel_thruste_1.setObjectName(_fromUtf8("fiel_thruste_1"))
        self.gridLayout_9.addWidget(self.fiel_thruste_1, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.line_4 = QtGui.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_40 = QtGui.QLabel(self.tab_2)
        self.label_40.setEnabled(True)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_11.addWidget(self.label_40)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.slider_thruster_16 = QtGui.QSlider(self.tab_2)
        self.slider_thruster_16.setEnabled(True)
        self.slider_thruster_16.setMinimum(-100)
        self.slider_thruster_16.setMaximum(100)
        self.slider_thruster_16.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thruster_16.setObjectName(_fromUtf8("slider_thruster_16"))
        self.gridLayout_10.addWidget(self.slider_thruster_16, 1, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.tab_2)
        self.label_41.setEnabled(True)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_10.addWidget(self.label_41, 0, 0, 1, 1)
        self.x_force = QtGui.QSpinBox(self.tab_2)
        self.x_force.setEnabled(True)
        self.x_force.setMinimum(-500)
        self.x_force.setMaximum(500)
        self.x_force.setObjectName(_fromUtf8("x_force"))
        self.gridLayout_10.addWidget(self.x_force, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.tab_2)
        self.label_42.setEnabled(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_10.addWidget(self.label_42, 1, 0, 1, 1)
        self.x_bal = QtGui.QSpinBox(self.tab_2)
        self.x_bal.setEnabled(True)
        self.x_bal.setMinimum(-100)
        self.x_bal.setMaximum(100)
        self.x_bal.setObjectName(_fromUtf8("x_bal"))
        self.gridLayout_10.addWidget(self.x_bal, 1, 1, 1, 1)
        self.slider_thruster_15 = QtGui.QSlider(self.tab_2)
        self.slider_thruster_15.setEnabled(True)
        self.slider_thruster_15.setMinimum(-500)
        self.slider_thruster_15.setMaximum(500)
        self.slider_thruster_15.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thruster_15.setObjectName(_fromUtf8("slider_thruster_15"))
        self.gridLayout_10.addWidget(self.slider_thruster_15, 0, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_10)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.label_43 = QtGui.QLabel(self.tab_2)
        self.label_43.setEnabled(True)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_10.addWidget(self.label_43)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_44 = QtGui.QLabel(self.tab_2)
        self.label_44.setEnabled(True)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_11.addWidget(self.label_44, 0, 0, 1, 1)
        self.y_force = QtGui.QSpinBox(self.tab_2)
        self.y_force.setEnabled(True)
        self.y_force.setMinimum(-500)
        self.y_force.setMaximum(500)
        self.y_force.setObjectName(_fromUtf8("y_force"))
        self.gridLayout_11.addWidget(self.y_force, 0, 1, 1, 1)
        self.slider_thruster_13 = QtGui.QSlider(self.tab_2)
        self.slider_thruster_13.setEnabled(True)
        self.slider_thruster_13.setMinimum(-500)
        self.slider_thruster_13.setMaximum(500)
        self.slider_thruster_13.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thruster_13.setObjectName(_fromUtf8("slider_thruster_13"))
        self.gridLayout_11.addWidget(self.slider_thruster_13, 0, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.tab_2)
        self.label_45.setEnabled(True)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_11.addWidget(self.label_45, 1, 0, 1, 1)
        self.y_bal = QtGui.QSpinBox(self.tab_2)
        self.y_bal.setEnabled(True)
        self.y_bal.setMinimum(-100)
        self.y_bal.setMaximum(100)
        self.y_bal.setObjectName(_fromUtf8("y_bal"))
        self.gridLayout_11.addWidget(self.y_bal, 1, 1, 1, 1)
        self.slider_thruster_14 = QtGui.QSlider(self.tab_2)
        self.slider_thruster_14.setEnabled(True)
        self.slider_thruster_14.setMinimum(-100)
        self.slider_thruster_14.setMaximum(100)
        self.slider_thruster_14.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thruster_14.setObjectName(_fromUtf8("slider_thruster_14"))
        self.gridLayout_11.addWidget(self.slider_thruster_14, 1, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_46 = QtGui.QLabel(self.tab_2)
        self.label_46.setEnabled(True)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.verticalLayout_12.addWidget(self.label_46)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_47 = QtGui.QLabel(self.tab_2)
        self.label_47.setEnabled(True)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_12.addWidget(self.label_47, 0, 0, 1, 1)
        self.z_force = QtGui.QSpinBox(self.tab_2)
        self.z_force.setEnabled(True)
        self.z_force.setMinimum(-500)
        self.z_force.setMaximum(500)
        self.z_force.setObjectName(_fromUtf8("z_force"))
        self.gridLayout_12.addWidget(self.z_force, 0, 1, 1, 1)
        self.slider_thruster_12 = QtGui.QSlider(self.tab_2)
        self.slider_thruster_12.setEnabled(True)
        self.slider_thruster_12.setMinimum(-500)
        self.slider_thruster_12.setMaximum(500)
        self.slider_thruster_12.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thruster_12.setObjectName(_fromUtf8("slider_thruster_12"))
        self.gridLayout_12.addWidget(self.slider_thruster_12, 0, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab_2)
        self.label_48.setEnabled(True)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_12.addWidget(self.label_48, 1, 0, 1, 1)
        self.z_bal = QtGui.QSpinBox(self.tab_2)
        self.z_bal.setEnabled(True)
        self.z_bal.setMinimum(-100)
        self.z_bal.setMaximum(100)
        self.z_bal.setObjectName(_fromUtf8("z_bal"))
        self.gridLayout_12.addWidget(self.z_bal, 1, 1, 1, 1)
        self.slider_thruster_11 = QtGui.QSlider(self.tab_2)
        self.slider_thruster_11.setEnabled(True)
        self.slider_thruster_11.setMinimum(-100)
        self.slider_thruster_11.setMaximum(100)
        self.slider_thruster_11.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thruster_11.setObjectName(_fromUtf8("slider_thruster_11"))
        self.gridLayout_12.addWidget(self.slider_thruster_11, 1, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_12)
        self.verticalLayout_9.addLayout(self.verticalLayout_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(2, 2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_9.addWidget(self.line_3)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_49 = QtGui.QLabel(self.tab_2)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.verticalLayout_13.addWidget(self.label_49)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.blinky_red = QtGui.QPushButton(self.tab_2)
        self.blinky_red.setObjectName(_fromUtf8("blinky_red"))
        self.horizontalLayout_7.addWidget(self.blinky_red)
        self.blinky_green = QtGui.QPushButton(self.tab_2)
        self.blinky_green.setObjectName(_fromUtf8("blinky_green"))
        self.horizontalLayout_7.addWidget(self.blinky_green)
        self.blinky_blue = QtGui.QPushButton(self.tab_2)
        self.blinky_blue.setObjectName(_fromUtf8("blinky_blue"))
        self.horizontalLayout_7.addWidget(self.blinky_blue)
        self.blinky_custom = QtGui.QPushButton(self.tab_2)
        self.blinky_custom.setObjectName(_fromUtf8("blinky_custom"))
        self.horizontalLayout_7.addWidget(self.blinky_custom)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.frame_5 = QtGui.QFrame(self.tab_2)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_14.addWidget(self.frame_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_50 = QtGui.QLabel(self.tab_2)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.verticalLayout_15.addWidget(self.label_50)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_51 = QtGui.QLabel(self.tab_2)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_13.addWidget(self.label_51, 0, 0, 1, 1)
        self.imu_z = QtGui.QLineEdit(self.tab_2)
        self.imu_z.setReadOnly(True)
        self.imu_z.setObjectName(_fromUtf8("imu_z"))
        self.gridLayout_13.addWidget(self.imu_z, 2, 1, 1, 1)
        self.imu_y = QtGui.QLineEdit(self.tab_2)
        self.imu_y.setReadOnly(True)
        self.imu_y.setObjectName(_fromUtf8("imu_y"))
        self.gridLayout_13.addWidget(self.imu_y, 1, 1, 1, 1)
        self.imu_x = QtGui.QLineEdit(self.tab_2)
        self.imu_x.setReadOnly(True)
        self.imu_x.setObjectName(_fromUtf8("imu_x"))
        self.gridLayout_13.addWidget(self.imu_x, 0, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.tab_2)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_13.addWidget(self.label_52, 1, 0, 1, 1)
        self.imu_w = QtGui.QLineEdit(self.tab_2)
        self.imu_w.setReadOnly(True)
        self.imu_w.setObjectName(_fromUtf8("imu_w"))
        self.gridLayout_13.addWidget(self.imu_w, 3, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.tab_2)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_13.addWidget(self.label_53, 2, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.tab_2)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_13.addWidget(self.label_54, 3, 0, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_13)
        self.horizontalLayout_8.addLayout(self.verticalLayout_15)
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_16.addWidget(self.line)
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_16.addWidget(self.frame_3)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(2, 4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 1, 1, 1)
        RoboticsMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RoboticsMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        RoboticsMain.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(RoboticsMain)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(RoboticsMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.front_pitch.cut)
        QtCore.QObject.connect(self.slider_thruster_15, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.x_force.setValue)
        QtCore.QObject.connect(self.x_force, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_thruster_15.setValue)
        QtCore.QObject.connect(self.x_bal, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_thruster_16.setValue)
        QtCore.QObject.connect(self.slider_thruster_16, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.x_bal.setValue)
        QtCore.QObject.connect(self.y_force, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_thruster_13.setValue)
        QtCore.QObject.connect(self.slider_thruster_13, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.y_force.setValue)
        QtCore.QObject.connect(self.y_bal, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_thruster_14.setValue)
        QtCore.QObject.connect(self.slider_thruster_14, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.y_bal.setValue)
        QtCore.QObject.connect(self.slider_thruster_12, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.z_force.setValue)
        QtCore.QObject.connect(self.z_force, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_thruster_12.setValue)
        QtCore.QObject.connect(self.z_bal, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_thruster_11.setValue)
        QtCore.QObject.connect(self.slider_thruster_11, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.z_bal.setValue)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), RoboticsMain.close)
        QtCore.QMetaObject.connectSlotsByName(RoboticsMain)

    def retranslateUi(self, RoboticsMain):
        RoboticsMain.setWindowTitle(QtGui.QApplication.translate("RoboticsMain", "Robotics Diagnostics and Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RoboticsMain", "<html><head/><body><p><span style=\" font-weight:600;\">Front CV Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RoboticsMain", "<html><head/><body><p><span style=\" font-weight:600;\">Down CV Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RoboticsMain", "Relative distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RoboticsMain", "Relative angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("RoboticsMain", "Relative distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("RoboticsMain", "Relative angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("RoboticsMain", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("RoboticsMain", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("RoboticsMain", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("RoboticsMain", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RoboticsMain", "<html><head/><body><p>Obj. Type</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("RoboticsMain", "<html><head/><body><p>Obj. Type</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("RoboticsMain", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("RoboticsMain", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("RoboticsMain", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("RoboticsMain", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("RoboticsMain", "Angular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("RoboticsMain", "Select Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.keyboardControl.setText(QtGui.QApplication.translate("RoboticsMain", "Keyboard", None, QtGui.QApplication.UnicodeUTF8))
        self.manualControl.setText(QtGui.QApplication.translate("RoboticsMain", "PS3", None, QtGui.QApplication.UnicodeUTF8))
        self.autonomousControl.setText(QtGui.QApplication.translate("RoboticsMain", "Autonomus", None, QtGui.QApplication.UnicodeUTF8))
        self.attemptPS3.setText(QtGui.QApplication.translate("RoboticsMain", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.preLeft.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.preRight.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.postLeft.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.preBottom.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.postRight.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.posBottom.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("RoboticsMain", "Planner Info", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_core1.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_core3.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_core4.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("RoboticsMain", "CPU Core 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("RoboticsMain", "CPU Core 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("RoboticsMain", "CPU Core 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("RoboticsMain", "CPU Core 2", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_core2.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("RoboticsMain", "HDD Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.hdd_temp_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("RoboticsMain", "Ambiant Temp.", None, QtGui.QApplication.UnicodeUTF8))
        self.bat_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "Battery 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RoboticsMain", "USB Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("RoboticsMain", "Battery 1", None, QtGui.QApplication.UnicodeUTF8))
        self.usb_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ambiant_temp_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.bat1_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.bat2_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RoboticsMain", "IMU Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("RoboticsMain", "System Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("RoboticsMain", "Thruster Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.ps3_present.setText(QtGui.QApplication.translate("RoboticsMain", "PS3 Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.thruster_stop.setText(QtGui.QApplication.translate("RoboticsMain", "Thruster stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("RoboticsMain", "Surge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("RoboticsMain", "Surge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("RoboticsMain", "Sway", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("RoboticsMain", "Heave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("RoboticsMain", "Heave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("RoboticsMain", "Sway", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("RoboticsMain", "Surge- Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("RoboticsMain", "Force", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("RoboticsMain", "Balance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("RoboticsMain", "Sway- Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("RoboticsMain", "Force", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("RoboticsMain", "Balance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("RoboticsMain", "Heave- Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("RoboticsMain", "Force", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("RoboticsMain", "Balance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("RoboticsMain", "Change blinky tape to", None, QtGui.QApplication.UnicodeUTF8))
        self.blinky_red.setText(QtGui.QApplication.translate("RoboticsMain", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.blinky_green.setText(QtGui.QApplication.translate("RoboticsMain", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.blinky_blue.setText(QtGui.QApplication.translate("RoboticsMain", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.blinky_custom.setText(QtGui.QApplication.translate("RoboticsMain", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("RoboticsMain", "IMU Raw Values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("RoboticsMain", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("RoboticsMain", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("RoboticsMain", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("RoboticsMain", "w", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("RoboticsMain", "Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RoboticsMain", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("RoboticsMain", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("RoboticsMain", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import GraphicsLayoutWidget
