# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resizable tentative 1.ui'
#
# Created: Tue Jan 21 11:20:18 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RoboticsMain(object):
    def setupUi(self, RoboticsMain):
        RoboticsMain.setObjectName(_fromUtf8("RoboticsMain"))
        RoboticsMain.resize(1024, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Only-Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RoboticsMain.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(RoboticsMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.mr_logo = QtGui.QLabel(self.centralwidget)
        self.mr_logo.setMaximumSize(QtCore.QSize(110, 100))
        self.mr_logo.setText(_fromUtf8(""))
        self.mr_logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Only-Logo.png")))
        self.mr_logo.setScaledContents(True)
        self.mr_logo.setObjectName(_fromUtf8("mr_logo"))
        self.verticalLayout_8.addWidget(self.mr_logo)
        self.bat_lbl = QtGui.QLabel(self.centralwidget)
        self.bat_lbl.setMaximumSize(QtCore.QSize(110, 16777215))
        self.bat_lbl.setObjectName(_fromUtf8("bat_lbl"))
        self.verticalLayout_8.addWidget(self.bat_lbl)
        self.battery_progress = QtGui.QProgressBar(self.centralwidget)
        self.battery_progress.setMaximumSize(QtCore.QSize(110, 16777215))
        self.battery_progress.setProperty("value", 24)
        self.battery_progress.setObjectName(_fromUtf8("battery_progress"))
        self.verticalLayout_8.addWidget(self.battery_progress)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.linearVertical = QtGui.QSlider(self.centralwidget)
        self.linearVertical.setOrientation(QtCore.Qt.Vertical)
        self.linearVertical.setObjectName(_fromUtf8("linearVertical"))
        self.gridLayout_3.addWidget(self.linearVertical, 1, 1, 2, 1)
        self.linearHorizantal = QtGui.QSlider(self.centralwidget)
        self.linearHorizantal.setOrientation(QtCore.Qt.Horizontal)
        self.linearHorizantal.setObjectName(_fromUtf8("linearHorizantal"))
        self.gridLayout_3.addWidget(self.linearHorizantal, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.linearX = QtGui.QLineEdit(self.centralwidget)
        self.linearX.setObjectName(_fromUtf8("linearX"))
        self.gridLayout_2.addWidget(self.linearX, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.linearY = QtGui.QLineEdit(self.centralwidget)
        self.linearY.setObjectName(_fromUtf8("linearY"))
        self.gridLayout_2.addWidget(self.linearY, 1, 1, 1, 1)
        self.linearZ = QtGui.QLineEdit(self.centralwidget)
        self.linearZ.setObjectName(_fromUtf8("linearZ"))
        self.gridLayout_2.addWidget(self.linearZ, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.angularX = QtGui.QLineEdit(self.centralwidget)
        self.angularX.setObjectName(_fromUtf8("angularX"))
        self.gridLayout_5.addWidget(self.angularX, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.angularY = QtGui.QLineEdit(self.centralwidget)
        self.angularY.setObjectName(_fromUtf8("angularY"))
        self.gridLayout_5.addWidget(self.angularY, 1, 1, 1, 1)
        self.angularZ = QtGui.QLineEdit(self.centralwidget)
        self.angularZ.setObjectName(_fromUtf8("angularZ"))
        self.gridLayout_5.addWidget(self.angularZ, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.angularVertical = QtGui.QSlider(self.centralwidget)
        self.angularVertical.setOrientation(QtCore.Qt.Vertical)
        self.angularVertical.setObjectName(_fromUtf8("angularVertical"))
        self.gridLayout_4.addWidget(self.angularVertical, 1, 1, 2, 1)
        self.angularHorizantal = QtGui.QSlider(self.centralwidget)
        self.angularHorizantal.setOrientation(QtCore.Qt.Horizontal)
        self.angularHorizantal.setObjectName(_fromUtf8("angularHorizantal"))
        self.gridLayout_4.addWidget(self.angularHorizantal, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(115, 0))
        self.label_19.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.keyboardControl = QtGui.QRadioButton(self.centralwidget)
        self.keyboardControl.setMinimumSize(QtCore.QSize(115, 0))
        self.keyboardControl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.keyboardControl.setObjectName(_fromUtf8("keyboardControl"))
        self.verticalLayout_7.addWidget(self.keyboardControl)
        self.manualControl = QtGui.QRadioButton(self.centralwidget)
        self.manualControl.setMinimumSize(QtCore.QSize(115, 0))
        self.manualControl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.manualControl.setObjectName(_fromUtf8("manualControl"))
        self.verticalLayout_7.addWidget(self.manualControl)
        self.autonomousControl = QtGui.QRadioButton(self.centralwidget)
        self.autonomousControl.setMinimumSize(QtCore.QSize(115, 0))
        self.autonomousControl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.autonomousControl.setObjectName(_fromUtf8("autonomousControl"))
        self.verticalLayout_7.addWidget(self.autonomousControl)
        self.attemptPS3 = QtGui.QPushButton(self.centralwidget)
        self.attemptPS3.setMinimumSize(QtCore.QSize(115, 0))
        self.attemptPS3.setMaximumSize(QtCore.QSize(115, 16777215))
        self.attemptPS3.setObjectName(_fromUtf8("attemptPS3"))
        self.verticalLayout_7.addWidget(self.attemptPS3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout123 = QtGui.QVBoxLayout()
        self.verticalLayout123.setObjectName(_fromUtf8("verticalLayout123"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout123.addWidget(self.label)
        self.imugraphics = GraphicsLayoutWidget(self.centralwidget)
        self.imugraphics.setMinimumSize(QtCore.QSize(350, 0))
        self.imugraphics.setObjectName(_fromUtf8("imugraphics"))
        self.verticalLayout123.addWidget(self.imugraphics)
        self.horizontalLayout_3.addLayout(self.verticalLayout123)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.pressure = GraphicsLayoutWidget(self.centralwidget)
        self.pressure.setMinimumSize(QtCore.QSize(158, 133))
        self.pressure.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pressure.setObjectName(_fromUtf8("pressure"))
        self.verticalLayout_3.addWidget(self.pressure)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.depth = GraphicsLayoutWidget(self.centralwidget)
        self.depth.setMinimumSize(QtCore.QSize(158, 133))
        self.depth.setMaximumSize(QtCore.QSize(16777215, 200))
        self.depth.setObjectName(_fromUtf8("depth"))
        self.verticalLayout_2.addWidget(self.depth)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 201))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.logObject = QtGui.QTextEdit(self.centralwidget)
        self.logObject.setMinimumSize(QtCore.QSize(160, 134))
        self.logObject.setMaximumSize(QtCore.QSize(16777215, 200))
        self.logObject.setObjectName(_fromUtf8("logObject"))
        self.horizontalLayout_2.addWidget(self.logObject)
        self.hydrophonegraph = GraphicsLayoutWidget(self.centralwidget)
        self.hydrophonegraph.setMinimumSize(QtCore.QSize(160, 134))
        self.hydrophonegraph.setMaximumSize(QtCore.QSize(16777215, 200))
        self.hydrophonegraph.setObjectName(_fromUtf8("hydrophonegraph"))
        self.horizontalLayout_2.addWidget(self.hydrophonegraph)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.postRight = QtGui.QLabel(self.centralwidget)
        self.postRight.setMinimumSize(QtCore.QSize(150, 0))
        self.postRight.setObjectName(_fromUtf8("postRight"))
        self.gridLayout.addWidget(self.postRight, 1, 1, 1, 1)
        self.preLeft = QtGui.QLabel(self.centralwidget)
        self.preLeft.setMinimumSize(QtCore.QSize(150, 0))
        self.preLeft.setObjectName(_fromUtf8("preLeft"))
        self.gridLayout.addWidget(self.preLeft, 0, 0, 1, 1)
        self.postLeft = QtGui.QLabel(self.centralwidget)
        self.postLeft.setMinimumSize(QtCore.QSize(150, 0))
        self.postLeft.setObjectName(_fromUtf8("postLeft"))
        self.gridLayout.addWidget(self.postLeft, 0, 1, 1, 1)
        self.preRight = QtGui.QLabel(self.centralwidget)
        self.preRight.setMinimumSize(QtCore.QSize(150, 0))
        self.preRight.setObjectName(_fromUtf8("preRight"))
        self.gridLayout.addWidget(self.preRight, 1, 0, 1, 1)
        self.posBottom = QtGui.QLabel(self.centralwidget)
        self.posBottom.setMinimumSize(QtCore.QSize(150, 0))
        self.posBottom.setObjectName(_fromUtf8("posBottom"))
        self.gridLayout.addWidget(self.posBottom, 2, 1, 1, 1)
        self.preBottom = QtGui.QLabel(self.centralwidget)
        self.preBottom.setMinimumSize(QtCore.QSize(150, 0))
        self.preBottom.setObjectName(_fromUtf8("preBottom"))
        self.gridLayout.addWidget(self.preBottom, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        RoboticsMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RoboticsMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        RoboticsMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RoboticsMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RoboticsMain.setStatusBar(self.statusbar)

        self.retranslateUi(RoboticsMain)
        QtCore.QMetaObject.connectSlotsByName(RoboticsMain)

    def retranslateUi(self, RoboticsMain):
        RoboticsMain.setWindowTitle(QtGui.QApplication.translate("RoboticsMain", "Robotics Diagnostics and Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.bat_lbl.setText(QtGui.QApplication.translate("RoboticsMain", "Battery State", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RoboticsMain", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RoboticsMain", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("RoboticsMain", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("RoboticsMain", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("RoboticsMain", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("RoboticsMain", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("RoboticsMain", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("RoboticsMain", "Angular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("RoboticsMain", "Select Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.keyboardControl.setText(QtGui.QApplication.translate("RoboticsMain", "Keyboard", None, QtGui.QApplication.UnicodeUTF8))
        self.manualControl.setText(QtGui.QApplication.translate("RoboticsMain", "PS3", None, QtGui.QApplication.UnicodeUTF8))
        self.autonomousControl.setText(QtGui.QApplication.translate("RoboticsMain", "Autonomus", None, QtGui.QApplication.UnicodeUTF8))
        self.attemptPS3.setText(QtGui.QApplication.translate("RoboticsMain", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RoboticsMain", "IMU Raw Readings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RoboticsMain", "Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RoboticsMain", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RoboticsMain", "IMU Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.postRight.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.preLeft.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.postLeft.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.preRight.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.posBottom.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.preBottom.setText(QtGui.QApplication.translate("RoboticsMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import GraphicsLayoutWidget
import Robotics_graphical_ressources_rc
